# site settings
title: Louie-David Desachy
subtitle: Phd Student in Applied Mathematics
email: louie-david.desachy@inria.fr
description: PhD student in Applied Mathematics for Medical Imaging at Inria and Université Paris Cité, I work on the development of generative approaches for modeling longitudinal trajectories and detecting anomalies in medical imaging data. My goal is to gain a deeper understanding of how pathologies evolve over time by combining advanced geometrical and statistical tools to support more precise and personalized diagnostics in healthcare .
baseurl:  # the subpath of your site, e.g. /blog
url: "louiedaviddesachy.github.io"# the base hostname & protocol for your site

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/LouieDavidD
  LinkedIn: https://www.linkedin.com/in/louie-david-desachy/
  Email: louie-david.desachy@inria.fr
  

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
